# Generated by Django 5.2.5 on 2025-10-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_thread_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
