# Generated by Django 5.2.5 on 2025-10-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_forum_geeksmodel_discussion_delete_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="email",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="link",
        ),
    ]
