# Generated by Django 5.2.5 on 2025-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_delete_geeksmodel_alter_forum_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="name",
            field=models.CharField(default="anonymous", max_length=200),
        ),
    ]
