# Generated by Django 5.2.5 on 2025-10-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_discussion_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
