# Generated by Django 5.2.7 on 2025-12-20 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('athlete_photo', models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
